GET_TABLE_KEYS <- function(overview_table, state_table){

  # This function generates the table keys of the overview and
  # state table for dynamic values in the text.
  
  # This function depends on the overview_table and state_table output of the 
  # 'GET_OVERVIEW_TABLE.R' and 'GET_STATE_TABLE.R' functions.
  
  #############################################################################
  
  pattern <- c(
               # overview_table keys
               
               "#Otc",
               "#Onc",
               "#Oth",
               "#Onh",
               "#Otd",
               "#Ond",
               "#Oi7",
               "#Oc7",
               
               # state_table keys
               
               "#BWtc",
               "#BWnc",
               "#BWth",
               "#BWnh",
               "#BWtd",
               "#BWnd",
               "#BWi7",
               "#BWc7",
               
               "#BYtc",
               "#BYnc",
               "#BYth",
               "#BYnh",
               "#BYtd",
               "#BYnd",
               "#BYi7",
               "#BYc7",
               
               "#BEtc",
               "#BEnc",
               "#BEth",
               "#BEnh",
               "#BEtd",
               "#BEnd",
               "#BEi7",
               "#BEc7",
               
               "#BBtc",
               "#BBnc",
               "#BBth",
               "#BBnh",
               "#BBtd",
               "#BBnd",
               "#BBi7",
               "#BBc7",
               
               "#HBtc",
               "#HBnc",
               "#HBth",
               "#HBnh",
               "#HBtd",
               "#HBnd",
               "#HBi7",
               "#HBc7",
               
               "#HHtc",
               "#HHnc",
               "#HHth",
               "#HHnh",
               "#HHtd",
               "#HHnd",
               "#HHi7",
               "#HHc7",
               
               "#HEtc",
               "#HEnc",
               "#HEth",
               "#HEnh",
               "#HEtd",
               "#HEnd",
               "#HEi7",
               "#HEc7",
               
               "#MVtc",
               "#MVnc",
               "#MVth",
               "#MVnh",
               "#MVtd",
               "#MVnd",
               "#MVi7",
               "#MVc7",
               
               "#NItc",
               "#NInc",
               "#NIth",
               "#NInh",
               "#NItd",
               "#NInd",
               "#NIi7",
               "#NIc7",
               
               "#NWtc",
               "#NWnc",
               "#NWth",
               "#NWnh",
               "#NWtd",
               "#NWnd",
               "#NWi7",
               "#NWc7",
               
               "#RPtc",
               "#RPnc",
               "#RPth",
               "#RPnh",
               "#RPtd",
               "#RPnd",
               "#RPi7",
               "#RPc7",
               
               "#SLtc",
               "#SLnc",
               "#SLth",
               "#SLnh",
               "#SLtd",
               "#SLnd",
               "#SLi7",
               "#SLc7",
               
               "#SNtc",
               "#SNnc",
               "#SNth",
               "#SNnh",
               "#SNtd",
               "#SNnd",
               "#SNi7",
               "#SNc7",
               
               "#STtc",
               "#STnc",
               "#STth",
               "#STnh",
               "#STtd",
               "#STnd",
               "#STi7",
               "#STc7",
               
               "#SHtc",
               "#SHnc",
               "#SHth",
               "#SHnh",
               "#SHtd",
               "#SHnd",
               "#SHi7",
               "#SHc7",
               
               "#THtc",
               "#THnc",
               "#THth",
               "#THnh",
               "#THtd",
               "#THnd",
               "#THi7",
               "#THc7"
  )
  
  replacement <- c(
                   #overview_table keys
                   
                   overview_table$`Total cases`,
                   overview_table$`New cases`,
                   overview_table$`Total hospitalizations`,
                   overview_table$`New hospitalizations`,
                   overview_table$`Total deaths`,
                   overview_table$`New deaths`,
                   overview_table$`7 Day Incidence`,
                   overview_table$`Change in 7 day incidence since yesterday`,
                   
                   #state_table keys
                   
                   state_table[['Total cases']][1],
                   state_table[['New cases']][1],
                   state_table[['Total hospitalizations']][1],
                   state_table[['New hospitalizations']][1],
                   state_table[['Total deaths']][1],
                   state_table[['New deaths']][1],
                   state_table[['7 Day Incidence']][1],
                   state_table[['Change in 7 day incidence since yesterday']][1],
                   
                   state_table[['Total cases']][2],
                   state_table[['New cases']][2],
                   state_table[['Total hospitalizations']][2],
                   state_table[['New hospitalizations']][2],
                   state_table[['Total deaths']][2],
                   state_table[['New deaths']][2],
                   state_table[['7 Day Incidence']][2],
                   state_table[['Change in 7 day incidence since yesterday']][2],
                   
                   state_table[['Total cases']][3],
                   state_table[['New cases']][3],
                   state_table[['Total hospitalizations']][3],
                   state_table[['New hospitalizations']][3],
                   state_table[['Total deaths']][3],
                   state_table[['New deaths']][3],
                   state_table[['7 Day Incidence']][3],
                   state_table[['Change in 7 day incidence since yesterday']][3],
                   
                   state_table[['Total cases']][4],
                   state_table[['New cases']][4],
                   state_table[['Total hospitalizations']][4],
                   state_table[['New hospitalizations']][4],
                   state_table[['Total deaths']][4],
                   state_table[['New deaths']][4],
                   state_table[['7 Day Incidence']][4],
                   state_table[['Change in 7 day incidence since yesterday']][4],
                   
                   state_table[['Total cases']][5],
                   state_table[['New cases']][5],
                   state_table[['Total hospitalizations']][5],
                   state_table[['New hospitalizations']][5],
                   state_table[['Total deaths']][5],
                   state_table[['New deaths']][5],
                   state_table[['7 Day Incidence']][5],
                   state_table[['Change in 7 day incidence since yesterday']][5],
                   
                   state_table[['Total cases']][6],
                   state_table[['New cases']][6],
                   state_table[['Total hospitalizations']][6],
                   state_table[['New hospitalizations']][6],
                   state_table[['Total deaths']][6],
                   state_table[['New deaths']][6],
                   state_table[['7 Day Incidence']][6],
                   state_table[['Change in 7 day incidence since yesterday']][6],
                   
                   state_table[['Total cases']][7],
                   state_table[['New cases']][7],
                   state_table[['Total hospitalizations']][7],
                   state_table[['New hospitalizations']][7],
                   state_table[['Total deaths']][7],
                   state_table[['New deaths']][7],
                   state_table[['7 Day Incidence']][7],
                   state_table[['Change in 7 day incidence since yesterday']][7],
                   
                   state_table[['Total cases']][8],
                   state_table[['New cases']][8],
                   state_table[['Total hospitalizations']][8],
                   state_table[['New hospitalizations']][8],
                   state_table[['Total deaths']][8],
                   state_table[['New deaths']][8],
                   state_table[['7 Day Incidence']][8],
                   state_table[['Change in 7 day incidence since yesterday']][8],
                   
                   state_table[['Total cases']][9],
                   state_table[['New cases']][9],
                   state_table[['Total hospitalizations']][9],
                   state_table[['New hospitalizations']][9],
                   state_table[['Total deaths']][9],
                   state_table[['New deaths']][9],
                   state_table[['7 Day Incidence']][9],
                   state_table[['Change in 7 day incidence since yesterday']][9],
                   
                   state_table[['Total cases']][10],
                   state_table[['New cases']][10],
                   state_table[['Total hospitalizations']][10],
                   state_table[['New hospitalizations']][10],
                   state_table[['Total deaths']][10],
                   state_table[['New deaths']][10],
                   state_table[['7 Day Incidence']][10],
                   state_table[['Change in 7 day incidence since yesterday']][10],
                   
                   state_table[['Total cases']][11],
                   state_table[['New cases']][11],
                   state_table[['Total hospitalizations']][11],
                   state_table[['New hospitalizations']][11],
                   state_table[['Total deaths']][11],
                   state_table[['New deaths']][11],
                   state_table[['7 Day Incidence']][11],
                   state_table[['Change in 7 day incidence since yesterday']][11],
                   
                   state_table[['Total cases']][12],
                   state_table[['New cases']][12],
                   state_table[['Total hospitalizations']][12],
                   state_table[['New hospitalizations']][12],
                   state_table[['Total deaths']][12],
                   state_table[['New deaths']][12],
                   state_table[['7 Day Incidence']][12],
                   state_table[['Change in 7 day incidence since yesterday']][12],
                   
                   state_table[['Total cases']][13],
                   state_table[['New cases']][13],
                   state_table[['Total hospitalizations']][13],
                   state_table[['New hospitalizations']][13],
                   state_table[['Total deaths']][13],
                   state_table[['New deaths']][13],
                   state_table[['7 Day Incidence']][13],
                   state_table[['Change in 7 day incidence since yesterday']][13],
                   
                   state_table[['Total cases']][14],
                   state_table[['New cases']][14],
                   state_table[['Total hospitalizations']][14],
                   state_table[['New hospitalizations']][14],
                   state_table[['Total deaths']][14],
                   state_table[['New deaths']][14],
                   state_table[['7 Day Incidence']][14],
                   state_table[['Change in 7 day incidence since yesterday']][14],
                   
                   state_table[['Total cases']][15],
                   state_table[['New cases']][15],
                   state_table[['Total hospitalizations']][15],
                   state_table[['New hospitalizations']][15],
                   state_table[['Total deaths']][15],
                   state_table[['New deaths']][15],
                   state_table[['7 Day Incidence']][15],
                   state_table[['Change in 7 day incidence since yesterday']][15],
                   
                   state_table[['Total cases']][16],
                   state_table[['New cases']][16],
                   state_table[['Total hospitalizations']][16],
                   state_table[['New hospitalizations']][16],
                   state_table[['Total deaths']][16],
                   state_table[['New deaths']][16],
                   state_table[['7 Day Incidence']][16],
                   state_table[['Change in 7 day incidence since yesterday']][16]
  )
  
  
  
  x <- list(pattern, replacement)
  
  return(x)
}